### ISSUE TITLE
LaTeX is not rendered

### ISSUE THREAD

**Issue by johnblommers** [bgallois/OpenJournal#1]
We typed the following into Openjournal 1.0.0:

`\\[\frac{\alpha}{\beta}\\]`

But the formula is not rendered. We see instead `\[\frac{\alpha}{\beta}\]`

We hoped to see:
![Screenshot from 2021-11-20 19-09-14](https://user-images.githubusercontent.com/8484427/142747976-513d14e3-43e0-4c3d-8253-84f8d7e94dc4.png)

**Comment by bgallois** [comment]
Thanks for the report. This issue was fixed with 4ecfcb6d1aa9f8b2f8196711d63be550165fa564, and it should be working with version 1.1.0 https://github.com/bgallois/OpenJournal/releases/tag/v1.1.0

**Comment by johnblommers** [comment]
Confirmed :-)
BTW I was momentarily confused because the About menu still shows 1.0.0 instead of 1.1.0 but definitely LaTeX works now.
